version: '3.9'

services:
  fastapi:
    container_name: webapp_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - unbsign-network

  postgres:
    container_name: psql_unbsign
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - unbsign-network
    ports:
      - "5431:5432"

networks:
  unbsign-network:
    driver: bridge